#################################
#             Backend           #
#################################
backend         = "xrender";
vsync           = false;
use-damage      = false;
unredir-if-possible = false;

#################################
#             Shadows           #
#################################
shadow         = true;
shadow-radius  = 12;
shadow-opacity = 0.5;
shadow-offset-x = -10;
shadow-offset-y = -10;

shadow-exclude = [
  "name    = 'Notification'",
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'",
  "_GTK_FRAME_EXTENTS@"
];

#################################
#             Fading            #
#################################
fading        = true;
fade-in-step  = 0.06;
fade-out-step = 0.06;
fade-delta    = 5;

#################################
#   Transparency / Opacity      #
#################################
active-opacity   = 1.0;
inactive-opacity = 0.95;
frame-opacity    = 1.0;

#################################
#        Opacity Rules          #
#################################
opacity-rule = [
  "92:class_g = 'Terminator'",
  "92:class_g = 'terminator'",
  "95:class_g = 'Code'",
  "95:class_g = 'code'"
];
